version: "3.7"
services:
  maria-database:
#    platform: linux/x86_64 #Mac M1칩 사용 제외하고는 주석처리
    image: mariadb:10.11.2
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: "allra-market"
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - 3306:3306
    volumes:
      - ./local-mariadb:/var/lib/mysql