spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/allra-market?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    enabled: true
    useNumbersForEnums: true
    tryItOutEnabled: true
  paths-to-match:
    - /api/v1/**
  show-actuator: true
  override-with-generic-response: true

payment:
    url: https://allra.free.beeceptor.com/api/v1/payment